id: P000641
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16793
  title: ཨ་གྲགས་གཟི་རྫོང་།
  author: ''
  volumes:
    75c4ea3075ab4b7984d4626694be5059:
      image_group_id: I1KG16930
      title: ''
      volume_number: 1
      total_pages: 422
