id: I4D44D73F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:55:51+00:00'
last_modified: '2022-06-07T12:32:16.743803+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16793
  title: ཨ་གྲགས་གཟི་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9C26:
      image_group_id: I1KG16930
      title: ''
      total_pages: 422
      order: 1
      base_file: 9C26.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
